# 数据库配置
HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'zlck_bbs'
USERNAME = 'root'
PASSWORD = 'root'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = True

SECERT_KEY = 'sdjf7123611naf'


#celery配置